{
"texts":{

"messJackpotTitle":"JACKPOT",
"messJackpot":"The game is linked to Mystery Jackpot.<br>At the end of each game the Player has a chance to win one of four<br>jackpot levels. The higher the bet, the higher the chance of winning<br>the jackpot.",
"messJackpotInt":"The game is connected to a mystery jackpot.<br>At the end of each game the player may enter a special bonus screen and play for any of the four jackpot levels. The higher the bet is, the higher is the probability for entering the bonus screen. 30 plates are displayed on the screen, activated one by one and the one that is active at the moment could be opened by pressing the SPACE or ENTER keyboard buttons. The player may open random plate at any time with the mouse.<br>If there is a jackpot symbol for any of the jackpot levels on the opened plate, the symbols of this type are increasing on the right side of the screen. When all the four symbols of the current jackpot level are collected, player hits the jackpot level and the bonus ends.",
"messKBDPlayTitle":"PLAYING WITH THE KEYBOARD",
"messKBDPlay":"Press ENTER or SPACE to spin the reels and collect winnings.",
"messDoubleName":"DOUBLE UP RULES",
"messDouble0":"After each game with a win less than ",
"messDouble1":" X TOTAL BET,<br>the player can take a chance to double the win and enter Double-UP<br>mode by pressing DOUBLE button. In the middle of the double-up<br>screen a card is displayed face down. The player should guess<br>whether the card is red or black, or the suit of the card<br>(by pressing the appropriate button). If the player has guessed<br> the correct card color, the gambled amount is multiplied by 2.<br>If the player has selected the correct card suit, the gambled amount is multiplied by 4. If the player has selected an incorrect card color or suit, the gambled amount is lost. At any time the player can exit the Double-Up mode and return to the game by collecting<br>his win with START button.<br>The player can gamble only half of his current win by<br>pressing HALF GAMBLE button.<br>The win doubling is allowed up to ",
"messDouble2":" x TOTAL BET.<br>When this limit is reached, the player collects the win<br>automatically and returns to the main game.",
"mess3Title":"HOW TO PLAY and SHORT KEYS",
"DENOMINATIONtext":"DENOMINATION SET TO ",
"DENOMtext":"DENOMINATION",
"CONGRATULATIONStext":"CONGRATULATIONS!<br>",
"YOU_HITtext":"YOU HIT THE ",
"JACKPOTtext":" JACKPOT",
"WONtext":"<br>YOU WON: ",
"JACKPOTSmess":["LEAD", "BRONZE", "SILVER", "GOLD"],
"selectBETtext":"SELECT BET",
"pressSTARTTtext":"PRESS START TO CONTINUE",
"returnToGametext":"RETURN<br>TO GAME",
"insertCREDITStext":"INSERT CREDITS",
"gameOVERtext":"GAME OVER",
"goodLUCKtext":"GOOD LUCK! ",
"cashOUTtext":"CASH OUT ",
"noWINtext":"No Win",
"SelectBetLinestext":"SELECT BET AND LINES",
"PayTABLEtext":"PAY TABLE",
"CONTROLStext":"CONTROLS",
"GamePAYStext":"GAME PAYS:",
"BETtext":"LINE BET",
"TotalBETtext":"TOTAL BET",
"MaxBETtext":"MAX BET",
"MinBETtext":"MIN BET",
"LastBETtext":"LAST BET",
"LINEStext":"LINES",
"LINEtext":"LINE",
"SCATTERStext":"SCATTERS: ",
"CREDITtext":"CREDIT",
"CASHtext":"CASH",
"WINtext":"WIN",
"LastWin":"LAST WIN",
"WinnerPaidtext":"WINNER PAID",
"WinDoubleUPtext":"WIN / DOUBLE UP",
"doubleUPtext":"DOUBLE UP",
"doubleREDtext":"RED",
"doubleBLACKtext":"BLACK",
"doubleHALFtext":"HALF GAMBLE",
"doubleTAKEtext":"TAKE WIN",
"doubleTakeWINtext":"TAKE WIN",
"double10text":"10 PREVIOUS CARDS",
"doubleLASTtext":"LAST CARD",
"doubleRBtext":"COLOR GAMBLE TO WIN",
"doubleSUITtext":"SUIT GAMBLE TO WIN",
"doubleAtext":"GAMBLE AMOUNT",
"doubleUpLIMITtext":"DOUBLE UP LIMIT IS REACHED",
"youWINtext":"YOU WIN!",
"dealerWINtext":"DEALER WINS",
"colorOrSUITtext":"CHOOSE COLOR OR SUIT",
"pressSTARTtext":"PRESS START",
"FREE_GAMEStext":"FREE GAMES",
"NEWtext":" NEW ",
"COLLECTEDtext":"YOU COLLECTED ",
"EXITtext":"EXIT",
"JPOTtext":"JPOT",
"autoONtext":"AUTO ON",
"autoOFFtext":"AUTO OFF",
"autoFASTtext":"AUTO<br>FAST",
"autoPlaytext":"AUTO<br>PLAY",
"gameMENUtext":"GAME<br>MENU",
"STOPautoPlaytext":"STOP<br>AUTO<br>PLAY",
"OFFtext":"OFF",
"SpinWintext":"SPIN WIN:",
"doubleBEText":"DOUBLE BET:",
"doubleWINtext":"DOUBLE WIN:",
"messStr00":"All Prizes in Credits.",
"messStr10":"",
"messStr11":"All wins begin with leftmost reel and pay left to right",
"messStr12":"on adjacent reels only",
"messStr2":", except scatters which pay on any position.",
"messStr3":"Only highest win paid on each played line. Malfunction voids all pays and plays.",
"treeOrMore":" ",
"freegames":" trigger the `Free Games` mode. The player is given ",
"freegames1":" free games.",
"all":"All the wins in the free games",
"mul":" are multiplied by ",
"ex":", except for ",
"newFreeGames1":"<br>If ",
"newFreeGames2":" appear on the screen during the free games,<br> ",
"newFreeGames3":" more free games are awarded.",
"autoplaysLeft1":" AUTOPLAYS LEFT ",
"autoplaysLeft2":" OF ",
"superGame_text1":" SUPER GAME ",
"superGame_text2":" OF ",
"freeGame_text1":" FREE GAME ",
"freeGame_text2":" OF ",
"endFreeGames_text":"END OF FREE GAMES.",
"playedFG1":"<br>",
"playedFG2":" FREE GAMES PLAYED",
"playedSG2":" SUPER GAMES PLAYED",
"buyIn_SELECT_CASHtext":"SELECT CASH",
"buyIn_BUY_INtext":"BUY IN"
,"FIXED":"FIXED"
,"ForAutoplay":"FOR AUTOPLAY PRESS PLAY FOR 2 sec."
,"LINES_SETbeg":"LINES SET to "
,"LINES_SETend":""
,"lastGame":"RECALL LAST GAME"
,"TURBOtext":"TURBO"
,"MULTIPLIERtext":"MULTIPLIER"
,"soundQuestion":"Play with sound?"
,"yes":"Yes",
"no":"No",
"extraBet_cw1":"Choose Extra Win Feature.<br><br>Play ",
"extraBet_cw2":" lines for ",
"extraBet_cw3":" credits",
"active":"active.",
"not_active":"not active.",
"free_spins":"free spins",
"FREE_spins_win":"FREE spins win",
"FREE_spinsLeft1":" FREE spins ",
"FREE_spinsLeft2":" OF ",
"playedFREE_spins1":"<br>",
"playedFREE_spins2":" FREE spins PLAYED",
"locked":"locked",
"Unlocked":"Unlocked"
,"NetworkProblеm":"Network problеm! Retrying..."
,"SoundLoadError": "Sound Load Error: "
,"SoundCodecError": "Sound Codec Error!"
,"NOT_FOUND":" NOT FOUND!! Close the game."
,"PleaseReload":"Please reload the game!"
,"InternalError":"Internal Error. (G012)"
}}
